"""add baby_id to events

Revision ID: 2e5ff7703cb2
Revises: c834c794ba75
Create Date: 2026-04-10 22:59:06.489433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5ff7703cb2'
down_revision: Union[str, Sequence[str], None] = 'c834c794ba75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add nullable first so existing rows don't immediately violate the constraint
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.String(length=36), nullable=True))

    # Backfill: assign each event the baby that its author is linked to
    op.execute("""
        UPDATE events
        SET baby_id = (
            SELECT baby_id FROM user_babies
            WHERE user_id = events.logged_by
            LIMIT 1
        )
    """)

    # Now enforce NOT NULL (batch_alter_table recreates the table for SQLite)
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('baby_id', existing_type=sa.String(length=36), nullable=False)
        batch_op.create_foreign_key(None, 'babies', ['baby_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('baby_id')

    # ### end Alembic commands ###
